name: fetch
on:
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - run: curl -L --fail --silent https://clinicaltrials.gov/api/v2/studies/NCT04779307 > nct04779307.json
      - uses: actions/upload-artifact@v4
        with:
          name: nct04779307
          path: nct04779307.json
