name: fetch-pdfs
on:
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - run: curl -L --fail --silent https://multi-sponsor-site-prod.s3.amazonaws.com/takeda/studies/attachments/MLN0002-3024-plain-language-summary.pdf > pls.pdf
      - run: curl -L --fail --silent https://multi-sponsor-site-prod.s3.amazonaws.com/takeda/studies/attachments/MLN0002-3024-clinical-study-report-redact.pdf > csr.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: |
            pls.pdf
            csr.pdf
